name: Links and Navigation Checks

# FOR TESTING PURPOSES THIS WILL NOT RUN IT IS CURRRENTLY IN THE PR AND DEPLOY YML FILES

on:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Links and Navigation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: Build navigation artifacts
        run: yarn buildNavigation

      - name: Normalize and check links
        run: |
          yarn normalizeLinks
          yarn checkLinks
