---
name: Test Links
on:
  workflow_call:

jobs:
  test-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Utils Repo
        uses: actions/checkout@v4
        with:
          repository: AdobeDocs/adp-devsite-utils
          path: utils
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.x'

      - name: Install Utils Dependencies
        run: |
          cd ./utils
          npm install
        
      - name: Test Links
        run: node ./utils/bin/checkLinks.js

